/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. Deliberately does not touch the database —
         *     a database outage must degrade features, not report the API dead.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Location Score
         * @description Score a candidate point for a business profile.
         *
         *     Contract notes for the implementer:
         *     - Validate the point against core.municipal_boundary FIRST; reject
         *       out-of-boundary points with 400, never silently score them.
         *     - Map the point to its analytics.analysis_cell, then read the
         *       precomputed analytics.location_score row for (cell, profile,
         *       active score_version, active data_release).
         *     - No spatial computation beyond point-in-polygon + cell lookup
         *       happens at request time.
         */
        get: operations["get_location_score_api_v1_locations_score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BusinessProfile
         * @enum {string}
         */
        BusinessProfile: "cafe" | "retail_shop" | "food_truck" | "pop_up";
        /** ComponentScore */
        ComponentScore: {
            /**
             * Key
             * @description e.g. pedestrian_demand, worker_demand, market_fit
             */
            key: string;
            /** Score */
            score: number;
            /** Weight */
            weight: number;
            /**
             * Evidence
             * @description Raw supporting values and percentiles; nulls mean 'not observed'
             */
            evidence?: {
                [key: string]: number | string | null;
            };
        };
        /**
         * Confidence
         * @description Shown separately from suitability — never blended invisibly.
         */
        Confidence: {
            /** Score */
            score: number;
            band: components["schemas"]["ConfidenceBand"];
            /**
             * Reasons
             * @description Human-readable evidence, e.g. 'Nearest sensor is 430 m away'
             */
            reasons: string[];
        };
        /**
         * ConfidenceBand
         * @enum {string}
         */
        ConfidenceBand: "high" | "medium" | "low" | "insufficient";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /** ScoreLocation */
        ScoreLocation: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Cell Id */
            cell_id: string;
        };
        /** ScoreResponse */
        ScoreResponse: {
            location: components["schemas"]["ScoreLocation"];
            profile: components["schemas"]["BusinessProfile"];
            /**
             * Score
             * @description Overall suitability. Null when critical evidence is missing — a withheld score is a valid product outcome, not an error.
             */
            score?: number | null;
            confidence: components["schemas"]["Confidence"];
            /** Components */
            components: components["schemas"]["ComponentScore"][];
            /** Top Drivers */
            top_drivers?: string[];
            /** Top Risks */
            top_risks?: string[];
            /**
             * Score Version
             * @description e.g. cafe-v1.0.0
             */
            score_version: string;
            /**
             * Data Release
             * @description e.g. melbourne-2026-07-25
             */
            data_release: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_location_score_api_v1_locations_score_get: {
        parameters: {
            query: {
                /** @description WGS84 latitude */
                lat: number;
                /** @description WGS84 longitude */
                lon: number;
                profile: components["schemas"]["BusinessProfile"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            /** @description Point outside the supported municipal boundary (FR-02) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Scoring pipeline not yet implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
