/**
 * Friendly aliases over the generated OpenAPI schema
 * (lib/api/schema.ts, regenerated by `make contracts`). Components must
 * import from here, never from schema.ts directly, so a contract
 * regeneration only ever touches this one adapter file.
 */
import type { components } from "./schema";

export type BusinessProfile = components["schemas"]["BusinessProfile"];
export type ConfidenceBand = components["schemas"]["ConfidenceBand"];
export type ComponentScore = components["schemas"]["ComponentScore"];
export type Confidence = components["schemas"]["Confidence"];
export type ScoreResponse = components["schemas"]["ScoreResponse"];
export type ProfileInfo = components["schemas"]["ProfileInfo"];
export type Coverage = components["schemas"]["Coverage"];

export const BUSINESS_PROFILES = [
  "cafe",
  "retail_shop",
  "food_truck",
  "pop_up",
] as const satisfies readonly BusinessProfile[];
